const NAME_OR_PASSWORD_IS_REQUIRED = '用户名或密码不能为空'
const USER_ALREADY_EXISTS ="用户名已存在"
const USERNAME_AND_PASSWORD_NOT_NULL = "用户名和密码不能为空"
const USER_UNEXISTS = "用户不存在"
const PASSWORD_ERROR ="用户名密码不匹配"
const UNAUTHOR = "未授权"
const UN_PREMISSION ="没有操作权限"

module.exports = {
    NAME_OR_PASSWORD_IS_REQUIRED,
    USER_ALREADY_EXISTS,
    USER_UNEXISTS,
    USERNAME_AND_PASSWORD_NOT_NULL,
    PASSWORD_ERROR,
    UNAUTHOR,
    UN_PREMISSION
}